name: Package/Index Helm Charts

on:
  push:
    paths:
        - 'terracotta-bank/**'
    #   - 'path/to/any/other/chart/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.4.1'  # Specify the Helm version

      - name: Package Helm Charts
        run: |
          mkdir -p .deploy
          paths=('terracotta-bank/*') # Define your paths here
          for path in "${paths[@]}"; do
            for d in $path; do
              if [ -d "$d" ]; then
                helm package "$d" -d .deploy
              fi
            done
          done

      - name: Update Helm Repo Index
        run: |
          helm repo index .deploy --url https://[username].github.io/[repository]

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          # Path of the directory containing the static assets.
          path: .deploy
          
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
