name: Package, Index, and Publish Multiple Helm Charts

on:
   push:
      paths:
         - 'terracotta-bank/**'
#         - 'path/to/any/other/chart/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.4.1'  # Specify the Helm version

      - name: Package Helm Charts
        run: |
          mkdir -p .deploy
          for d in path/to/chart*; do
            if [ -d "$d" ]; then
              helm package "$d" -d .deploy
            fi
          done

      - name: Update Helm Repo Index
        run: |
          helm repo index .deploy --url https://[username].github.io/[repository]
